version: "3.1"

services:
  node:
    build: .
    image: myffcs
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
